INSERT INTO `TB_USER_PROFILE` (`USER_PROFILE_ID`, `USER_PROFILE_TYPE`)
VALUES
	(1, 'PLAYER'),
	(2, 'CAPTAIN'),
	(3, 'DIRECTOR'),
	(4, 'COACH'),
	(5, 'REFEREE'),
	(6, 'OWNER'),
	(7, 'MASTER');

	
	INSERT INTO `TB_SPORTS_CLUB_PROFILE` (`SPORTS_CLUB_PROFILE_ID`, `SPORTS_CLUB_PROFILE_TYPE`)
VALUES
	(1, 'UNCHOSEN'),
	(2, 'BALLING'),
	(3, 'TENNIS'),
	(4, 'BICYCLE'),
	(5, 'PINGPONG'),
	(6, 'BADMINTON');	